server:
  port: 8085

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    server:
      weflux:
        routes:
          - id: ms-doctores
            uri: lb://ms-doctores
            predicate:
              - Path=/api/doctores/**
          - id: ms-citas
            uri: lb://ms-citas
            predicate:
              - Path=/api/citas/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true